// react-admin/src/views/system/menu/index.tsx
/**
 * 菜单管理
 * ---------------------------------------------
 * 对应 vue3-admin views/system/menu/index.vue：
 * 筛选卡片（关键字）+ 表格卡片（新增 / 展开全部 / 收起全部 + 树形 ProTable），
 * 侧边栏展示列内联 Switch 直接切换；任何变更后刷新侧边栏导航并失效菜单缓存。
 */
import { useState } from 'react'
import type { Key } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button, Form, Input, Switch } from 'antd'
import { PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import ProTable from '@/components/ProTable'
import type { ProTableColumn } from '@/components/ProTable'
import DynamicIcon from '@/components/DynamicIcon'
import type { MenuTreeNode } from '@/api/system/sysMenu'
import {
  deleteMenu,
  fetchMenuEntity,
  fetchMenuTree,
  menuKeys,
  updateMenu,
} from '@/api/system/sysMenu'
import { usePermissionStore } from '@/stores/modules/permission'
import { confirm, message, withLoading } from '@/utils/feedback'
import MenuForm from './components/MenuForm'

/** 树形数据全部节点 id（展开全部用） */
function collectKeys(nodes: MenuTreeNode[]): Key[] {
  return nodes.flatMap(node => [node.id, ...(node.children ? collectKeys(node.children) : [])])
}

export default function SystemMenuListPage() {
  const queryClient = useQueryClient()
  const refreshMenu = usePermissionStore(s => s.refreshMenu)

  /** 输入框值（未提交） */
  const [keyword, setKeyword] = useState('')
  /** 已提交的查询关键字（入 queryKey） */
  const [searchKey, setSearchKey] = useState('')
  /** 展开态：null 表示未交互 → 默认全部展开 */
  const [expandedKeys, setExpandedKeys] = useState<Key[] | null>(null)
  const [switchingId, setSwitchingId] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [editingRow, setEditingRow] = useState<MenuTreeNode | null>(null)
  /** 每次打开表单自增，作为 MenuForm 的 key 触发重挂载（表单回到初始态） */
  const [formKey, setFormKey] = useState(0)

  const { data, isFetching } = useQuery({
    queryKey: [...menuKeys.trees(), searchKey],
    queryFn: ({ signal }) => fetchMenuTree({ searchKey: searchKey || undefined }, signal),
  })

  const treeData = data ?? []
  const effectiveExpandedKeys = expandedKeys ?? collectKeys(treeData)

  const columns: ProTableColumn<MenuTreeNode>[] = [
    { title: '菜单标题', dataIndex: 'title', width: 200 },
    { title: '路由路径', dataIndex: 'path', width: 180 },
    {
      title: '图标',
      dataIndex: 'icon',
      width: 80,
      align: 'center',
      render: (_, row) => <DynamicIcon name={row.icon} className="text-lg" />,
    },
    {
      title: '侧边栏展示',
      dataIndex: 'isMenuShow',
      width: 130,
      align: 'center',
      render: (_, row) => (
        <Switch
          size="small"
          checked={row.isMenuShow !== false}
          loading={switchingId === row.id}
          onChange={checked => handleToggleShow(row, checked)}
        />
      ),
    },
    { title: '排序号', dataIndex: 'order', width: 90, align: 'center' },
    {
      title: '操作',
      key: 'action',
      width: 160,
      align: 'center',
      fixed: 'right',
      render: (_, row) => (
        <>
          <Button type="link" size="small" onClick={() => handleEdit(row)}>
            编辑
          </Button>
          <Button
            type="link"
            size="small"
            danger
            disabled={row._disabled}
            onClick={() => void handleDelete(row)}
          >
            删除
          </Button>
        </>
      ),
    },
  ]

  /** 侧边栏展示开关：先取实体再整体提交（对齐 UpdateMenu 契约，避免只传增量字段） */
  const toggleShowMutation = useMutation({
    mutationFn: async ({ rowId, isMenuShow }: { rowId: string; isMenuShow: boolean }) => {
      const entity = await fetchMenuEntity(rowId)
      await updateMenu({
        id: rowId,
        title: entity.title,
        path: entity.path ?? '',
        icon: entity.icon ?? '',
        order: entity.order ?? 99,
        isMenuShow,
        parentId: entity.parent?.id ?? null,
      })
    },
    onMutate: ({ rowId }) => setSwitchingId(rowId),
    onSuccess: () => handleChanged(),
    onError: () => message.error('操作失败'),
    onSettled: () => setSwitchingId(''),
  })

  /** 菜单数据变更后：刷新侧边栏导航 + 失效菜单缓存 */
  async function handleChanged() {
    await refreshMenu()
    await queryClient.invalidateQueries({ queryKey: menuKeys.trees() })
  }

  /** 查询：提交关键字（树结构变化后回到全展开） */
  function handleSearch() {
    setSearchKey(keyword)
    setExpandedKeys(null)
  }

  function handleReset() {
    setKeyword('')
    setSearchKey('')
    setExpandedKeys(null)
  }

  function handleAdd() {
    setEditingRow(null)
    setFormKey(key => key + 1)
    setFormOpen(true)
  }

  function handleEdit(row: MenuTreeNode) {
    setEditingRow(row)
    setFormKey(key => key + 1)
    setFormOpen(true)
  }

  function handleExpandAll() {
    setExpandedKeys(collectKeys(treeData))
  }

  function handleCollapseAll() {
    setExpandedKeys([])
  }

  function handleToggleShow(row: MenuTreeNode, isMenuShow: boolean) {
    toggleShowMutation.mutate({ rowId: row.id, isMenuShow })
  }

  /** 删除菜单（系统内置菜单不可删除，按钮已禁用） */
  async function handleDelete(row: MenuTreeNode) {
    const ok = await confirm(`确定删除菜单「${row.title}」？`, '删除确认', {
      okText: '删除',
      okButtonProps: { danger: true },
    })
    if (!ok) return
    await withLoading(deleteMenu({ ids: [row.id] }), '删除中...')
    message.success('删除成功')
    await handleChanged()
  }

  function handleSuccess() {
    void handleChanged()
  }

  return (
    <div className="h-page flex flex-col">
      <div className="panel-card mb-4 shrink-0">
        {/* 筛选区：一行三列（每项占 1/3），按钮组落在筛选条件之后的列内右对齐 */}
        <Form labelCol={{ flex: '0 0 80px' }} wrapperCol={{ flex: '1 1 0%' }}>
          <div className="grid grid-cols-3 gap-x-4 gap-y-4">
            <Form.Item label="关键字" className="!mb-0">
              <Input
                className="w-full"
                placeholder="请输入菜单名称或路由"
                allowClear
                value={keyword}
                onChange={e => setKeyword(e.target.value)}
                onPressEnter={handleSearch}
                onClear={handleReset}
              />
            </Form.Item>
            <Form.Item className="col-start-2 !mb-0">
              <div className="flex gap-3">
                <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                  查询
                </Button>
                <Button icon={<ReloadOutlined />} onClick={handleReset}>
                  重置
                </Button>
              </div>
            </Form.Item>
          </div>
        </Form>
      </div>

      <div className="panel-card flex min-h-0 flex-1 flex-col">
        <div className="mb-4 flex shrink-0 items-center gap-3">
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            新增
          </Button>
          <Button onClick={handleExpandAll}>展开全部</Button>
          <Button onClick={handleCollapseAll}>收起全部</Button>
        </div>

        <ProTable<MenuTreeNode>
          autoHeight
          columns={columns}
          dataSource={treeData}
          loading={isFetching}
          scroll={{ x: 900 }}
          expandable={{
            expandedRowKeys: effectiveExpandedKeys,
            onExpandedRowsChange: keys => setExpandedKeys([...keys]),
          }}
        />
      </div>

      <MenuForm
        key={formKey}
        open={formOpen}
        editingRow={editingRow}
        onClose={() => setFormOpen(false)}
        onSuccess={handleSuccess}
      />
    </div>
  )
}

// vue3-admin/src/views/system/menu/index.vue
<script setup lang="ts">
import { ref, useTemplateRef, computed } from 'vue'
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query'
import ProTable from '@/components/ProTable/index.vue'
import type { ProTableColumn } from '@/components/ProTable/index.vue'
import iconMap from '@/icons'
import type { MenuTreeNode } from '@/api/system/sysMenu'
import { menuKeys } from '@/api/system/sysMenu'
import * as sysMenuApi from '@/api/system/sysMenu'
import { usePermissionStore } from '@/stores/modules/permission'
import { confirm, message, withLoading } from '@/utils/feedback'
import MenuForm from './components/MenuForm.vue'

const queryClient = useQueryClient()
const permissionStore = usePermissionStore()

const searchKey = ref('')
const switchingId = ref('')
const proTableRef = useTemplateRef('proTableRef')
const menuFormRef = useTemplateRef('menuFormRef')

const {
  data,
  isFetching: loading,
  refetch,
} = useQuery({
  queryKey: menuKeys.trees(),
  queryFn: ({ signal }) => sysMenuApi.fetchMenuTree({ searchKey: searchKey.value }, signal),
})

const treeData = computed(() => data.value ?? [])

const toggleShowMutation = useMutation({
  mutationFn: async ({ rowId, val }: { rowId: string; val: boolean }) => {
    const entity = await sysMenuApi.fetchMenuEntity(rowId)
    if (!entity) throw new Error()
    await sysMenuApi.updateMenu({
      id: rowId,
      title: entity.title || '',
      path: entity.path || '',
      icon: entity.icon || '',
      order: entity.order ?? 99,
      isMenuShow: val,
      parentId: entity.parent?.id ?? null,
    })
  },
  onMutate: ({ rowId }) => {
    switchingId.value = rowId
  },
  onSuccess: () => onMenuChanged(),
  onError: () => {
    message.error('操作失败')
  },
  onSettled: () => {
    switchingId.value = ''
  },
})

const columns: ProTableColumn<MenuTreeNode>[] = [
  { prop: 'title', label: '菜单标题', minWidth: 160 },
  { prop: 'path', label: '路由路径', minWidth: 140 },
  { label: '图标', width: 80, align: 'center', slot: 'icon' },
  { label: '侧边栏展示', width: 130, align: 'center', slot: 'show' },
  { prop: 'order', label: '排序号', width: 80, align: 'center' },
  { label: '操作', width: 160, align: 'center', fixed: 'right', slot: 'action' },
]

/** 菜单数据变更后刷新侧边栏导航 + 表格数据 */
async function onMenuChanged() {
  await permissionStore.refreshMenu()
  await queryClient.invalidateQueries({ queryKey: menuKeys.trees() })
}

function toggleRows(rows: MenuTreeNode[], expanded: boolean) {
  rows.forEach(row => {
    proTableRef.value?.elTableRef?.toggleRowExpansion(row, expanded)
    if (row.children?.length) {
      toggleRows(row.children, expanded)
    }
  })
}

function handleSearch() {
  refetch()
}

function handleReset() {
  searchKey.value = ''
  handleSearch()
}

function handleExpandAll() {
  toggleRows(treeData.value ?? [], true)
}

function handleCollapseAll() {
  toggleRows(treeData.value ?? [], false)
}

/** 打开新增菜单抽屉 */
function openCreate() {
  menuFormRef.value?.open()
}

/** 打开编辑菜单抽屉 */
function openEdit(row: MenuTreeNode) {
  menuFormRef.value?.open(row)
}

function handleSuccess() {
  onMenuChanged()
}

/** 切换侧边栏展示状态 */
async function handleToggleShow(row: MenuTreeNode, val: boolean) {
  toggleShowMutation.mutate({ rowId: row.id, val })
}

/** 删除菜单 */
async function handleDelete(row: MenuTreeNode) {
  if (row._disabled) return
  const ok = await confirm(`确定删除菜单「${row.title}」？`, '删除确认', {
    type: 'error',
    confirmButtonText: '删除',
  })
  if (!ok) return
  await withLoading(sysMenuApi.deleteMenu({ ids: [row.id] }), '删除中...')
  message.success('删除成功')
  await onMenuChanged()
}
</script>

<template>
  <div class="flex h-page flex-col">
    <div class="panel-card mb-4 shrink-0">
      <div class="flex items-center">
        <el-input
          v-model="searchKey"
          class="w-60!"
          placeholder="搜索菜单名称或路由"
          clearable
          @keyup.enter="handleSearch"
        />
        <el-button class="ml-3" type="primary" @click="handleSearch">
          <template #icon><IconEpSearch /></template>
          查询
        </el-button>
        <el-button @click="handleReset">
          <template #icon><IconEpRefresh /></template>
          重置
        </el-button>
      </div>
    </div>
    <div class="panel-card flex min-h-0 flex-1 flex-col">
      <div class="mb-4 flex items-center">
        <el-button type="primary" @click="openCreate">
          <template #icon><IconEpPlus /></template>
          新增
        </el-button>
        <el-button @click="handleExpandAll">
          <template #icon><IconRiExpandVerticalLine /></template>
          展开全部
        </el-button>
        <el-button @click="handleCollapseAll">
          <template #icon><IconRiCollapseVerticalLine /></template>
          收起全部
        </el-button>
      </div>
      <ProTable
        ref="proTableRef"
        auto-height
        :columns="columns"
        :data="treeData"
        :loading="loading"
        default-expand-all
      >
        <template #icon="{ row }">
          <el-icon v-if="row.icon && iconMap[row.icon]" :size="18">
            <component :is="iconMap[row.icon]" />
          </el-icon>
          <span v-else class="text-xs text-gray-400">-</span>
        </template>
        <template #show="{ row }">
          <el-switch
            :model-value="row.isMenuShow !== false"
            :loading="switchingId === row.id"
            @change="val => handleToggleShow(row, val === true)"
          />
        </template>
        <template #action="{ row }">
          <el-button type="primary" link @click="openEdit(row)">编辑</el-button>
          <el-button type="danger" link :disabled="row._disabled" @click="handleDelete(row)"
            >删除</el-button
          >
        </template>
      </ProTable>
    </div>
  </div>
  <MenuForm ref="menuFormRef" @success="handleSuccess" />
</template>

<style lang="scss" scoped></style>
