// vue3-admin/src/views/system/user/index.vue
<script setup lang="ts">
import { ref, computed, useTemplateRef } from 'vue'
import { useQuery, keepPreviousData, useQueryClient } from '@tanstack/vue-query'
import ProTable from '@/components/ProTable/index.vue'
import type { ProTableColumn } from '@/components/ProTable/index.vue'
import type { UserListItem } from '@/api/system/sysUser'
import { userKeys } from '@/api/system/sysUser'
import * as sysUserApi from '@/api/system/sysUser'
import { confirm, message, withLoading } from '@/utils/feedback'
import { resolveFileUrl } from '@/utils/file'
import UserForm from './components/UserForm.vue'

const queryClient = useQueryClient()

const searchKey = ref('')
const page = ref(1)
const pageSize = ref(10)
const selectedRows = ref<UserListItem[]>([])
const userFormRef = useTemplateRef('userFormRef')

const {
  data: listRes,
  isFetching: loading,
  refetch,
} = useQuery({
  queryKey: [...userKeys.lists(), page, pageSize],
  queryFn: ({ signal }) =>
    sysUserApi.fetchUserList(
      {
        page: page.value,
        rows: pageSize.value,
        searchKey: searchKey.value || undefined,
      },
      signal,
    ),
  placeholderData: keepPreviousData,
})

const tableData = computed(() => listRes.value?.list ?? [])
const total = computed(() => listRes.value?.total ?? 0)

const columns: ProTableColumn<UserListItem>[] = [
  {
    type: 'selection',
    width: 55,
    align: 'center',
    selectable: row => row._disabled,
  },
  { prop: 'name', label: '姓名' },
  { prop: 'id', label: '账号' },
  { label: '头像', align: 'center', slot: 'avatar' },
  { label: '状态', align: 'center', slot: 'status' },
  { label: '角色', slot: 'roles' },
  { label: '操作', width: 160, align: 'center', fixed: 'right', slot: 'action' },
]

/** 删除单个或批量账户 */
async function handleDelete(ids: string[], name?: string) {
  const tip = name ? `确定删除账户「${name}」？` : `确定删除选中的 ${ids.length} 个账户？`
  const ok = await confirm(tip, '删除确认', {
    type: 'error',
    confirmButtonText: '删除',
  })
  if (!ok) return
  await withLoading(sysUserApi.deleteUser({ ids }), '删除中...')
  message.success('删除成功')
  await queryClient.invalidateQueries({ queryKey: userKeys.lists() })
  selectedRows.value = []
}

function handleSearch() {
  if (page.value === 1) refetch()
  else page.value = 1
}

function handleReset() {
  searchKey.value = ''
  if (page.value === 1) refetch()
  else page.value = 1
}

function handleSelectionChange(rows: UserListItem[]) {
  selectedRows.value = rows
}

/** 新增账户 */
function handleAdd() {
  userFormRef.value?.open()
}

/** 批量删除账户 */
function handleBatchDelete() {
  if (!selectedRows.value.length) {
    message.warning('请先勾选要删除的账户')
    return
  }
  handleDelete(selectedRows.value.map(row => row.id))
}

function handleEdit(row: UserListItem) {
  userFormRef.value?.open(row)
}

function handleSuccess() {
  queryClient.invalidateQueries({ queryKey: userKeys.lists() })
}
</script>

<template>
  <div class="flex h-page flex-col">
    <div class="panel-card mb-4 shrink-0">
      <div class="flex items-center">
        <el-input
          v-model="searchKey"
          class="w-60!"
          placeholder="请输入账号或姓名"
          clearable
          @keyup.enter="handleSearch"
          @clear="handleReset"
        />
        <el-button class="ml-3" type="primary" @click="handleSearch">
          <template #icon><IconEpSearch /></template>
          查询
        </el-button>
        <el-button @click="handleReset">
          <template #icon><IconEpRefresh /></template>
          重置
        </el-button>
      </div>
    </div>

    <div class="panel-card flex min-h-0 flex-1 flex-col">
      <div class="mb-4 flex items-center">
        <el-button type="danger" :disabled="!selectedRows.length" @click="handleBatchDelete">
          <template #icon><IconEpDelete /></template>
          批量删除
        </el-button>
        <el-button type="primary" @click="handleAdd">
          <template #icon><IconEpPlus /></template>
          新增
        </el-button>
      </div>

      <ProTable
        auto-height
        v-model:current-page="page"
        v-model:page-size="pageSize"
        :columns="columns"
        :data="tableData"
        :loading="loading"
        :total="total"
        paginated
        @selection-change="handleSelectionChange"
      >
        <template #avatar="{ row }">
          <el-avatar :src="resolveFileUrl(row.avatar)" :size="34">
            <IconEpUser />
          </el-avatar>
        </template>

        <template #status="{ row }">
          <el-tag :type="row.status === 1 ? 'success' : 'danger'">
            {{ row.statusName }}
          </el-tag>
        </template>

        <template #roles="{ row }">
          <el-tag v-for="role in row.sysRoleUsers" :key="role.roleId" class="mr-1">
            {{ role.roleName }}
          </el-tag>
        </template>

        <template #action="{ row }">
          <el-button
            v-if="row.isDelHandle !== false"
            type="primary"
            link
            @click="handleEdit(row)"
            :disabled="!row._disabled"
          >
            编辑
          </el-button>
          <el-button
            v-if="row.isDelHandle !== false"
            type="danger"
            link
            @click="handleDelete([row.id], row.name)"
            :disabled="!row._disabled"
          >
            删除
          </el-button>
        </template>
      </ProTable>
    </div>
  </div>
  <UserForm ref="userFormRef" @success="handleSuccess" />
</template>

<style lang="scss" scoped></style>

// react-admin/src/views/system/user/index.tsx
/**
 * 账户管理
 * ---------------------------------------------
 * 对应 vue3-admin views/system/user/index.vue：
 * 筛选卡片（账号/姓名关键字）+ 表格卡片（批量删除 / 新增 + ProTable + 分页），
 * 外层 flex h-page 满高布局、表格满高内部滚动。
 *
 * 筛选条件以「已提交值」入 queryKey（输入框值不入），查询/重置同时回到第 1 页，
 * 既避免逐字触发请求，也避免 refetch 闭包读到旧值。
 */
import { useState } from 'react'
import type { Key } from 'react'
import { keepPreviousData, useQuery, useQueryClient } from '@tanstack/react-query'
import { Avatar, Button, Form, Input, Tag } from 'antd'
import {
  DeleteOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UserOutlined,
} from '@ant-design/icons'
import ProTable from '@/components/ProTable'
import type { ProTableColumn } from '@/components/ProTable'
import type { UserListItem } from '@/api/system/sysUser'
import { deleteUser, fetchUserList, userKeys } from '@/api/system/sysUser'
import { confirm, message, withLoading } from '@/utils/feedback'
import { resolveFileUrl } from '@/utils/file'
import UserForm from './components/UserForm'

export default function SystemUserListPage() {
  const queryClient = useQueryClient()

  /** 输入框值（未提交） */
  const [keyword, setKeyword] = useState('')
  /** 已提交的查询关键字（入 queryKey） */
  const [searchKey, setSearchKey] = useState('')
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [selectedRowKeys, setSelectedRowKeys] = useState<Key[]>([])
  const [selectedRows, setSelectedRows] = useState<UserListItem[]>([])
  const [formOpen, setFormOpen] = useState(false)
  const [editingRow, setEditingRow] = useState<UserListItem | null>(null)
  /** 每次打开表单自增，作为 UserForm 的 key 触发重挂载（表单与本地状态回到初始态） */
  const [formKey, setFormKey] = useState(0)

  const { data: listRes, isFetching } = useQuery({
    queryKey: [...userKeys.lists(), page, pageSize, searchKey],
    queryFn: ({ signal }) =>
      fetchUserList({ page, rows: pageSize, searchKey: searchKey || undefined }, signal),
    placeholderData: keepPreviousData,
  })

  const tableData = listRes?.list ?? []
  const total = listRes?.total ?? 0

  const columns: ProTableColumn<UserListItem>[] = [
    { title: '姓名', dataIndex: 'name' },
    { title: '账号', dataIndex: 'id' },
    {
      title: '头像',
      dataIndex: 'avatar',
      width: 90,
      align: 'center',
      render: (_, row) => (
        <Avatar size={34} src={resolveFileUrl(row.avatar) || undefined} icon={<UserOutlined />} />
      ),
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      type: 'tag',
      valueEnum: {
        1: { text: '启用', type: 'success' },
        [-1]: { text: '禁用', type: 'error' },
      },
    },
    {
      title: '角色',
      dataIndex: 'sysRoleUsers',
      render: (_, row) =>
        row.sysRoleUsers.map(role => <Tag key={role.roleId}>{role.roleName}</Tag>),
    },
    {
      title: '操作',
      key: 'action',
      width: 160,
      align: 'center',
      fixed: 'right',
      render: (_, row) =>
        row.isDelHandle === false ? null : (
          <>
            <Button
              type="link"
              size="small"
              disabled={!row._disabled}
              onClick={() => handleEdit(row)}
            >
              编辑
            </Button>
            <Button
              type="link"
              size="small"
              danger
              disabled={!row._disabled}
              onClick={() => void handleDelete([row.id], row.name)}
            >
              删除
            </Button>
          </>
        ),
    },
  ]

  /** 删除单个或批量账户 */
  async function handleDelete(ids: string[], name?: string) {
    const tip = name ? `确定删除账户「${name}」？` : `确定删除选中的 ${ids.length} 个账户？`
    const ok = await confirm(tip, '删除确认', {
      okText: '删除',
      okButtonProps: { danger: true },
    })
    if (!ok) return
    await withLoading(deleteUser({ ids }), '删除中...')
    message.success('删除成功')
    await queryClient.invalidateQueries({ queryKey: userKeys.lists() })
    setSelectedRowKeys([])
    setSelectedRows([])
  }

  /** 查询：提交关键字并回到第 1 页 */
  function handleSearch() {
    setSearchKey(keyword)
    setPage(1)
  }

  function handleReset() {
    setKeyword('')
    setSearchKey('')
    setPage(1)
  }

  function handleAdd() {
    setEditingRow(null)
    setFormKey(key => key + 1)
    setFormOpen(true)
  }

  function handleEdit(row: UserListItem) {
    setEditingRow(row)
    setFormKey(key => key + 1)
    setFormOpen(true)
  }

  /** 批量删除账户 */
  function handleBatchDelete() {
    if (!selectedRows.length) {
      message.warning('请先勾选要删除的账户')
      return
    }
    void handleDelete(selectedRows.map(row => row.id))
  }

  function handleSuccess() {
    void queryClient.invalidateQueries({ queryKey: userKeys.lists() })
  }

  return (
    <div className="h-page flex flex-col">
      <div className="panel-card mb-4 shrink-0">
        {/* 筛选区：一行三列（每项占 1/3），按钮组落在第三列右对齐 */}
        <Form labelCol={{ flex: '0 0 80px' }} wrapperCol={{ flex: '1 1 0%' }}>
          <div className="grid grid-cols-3 gap-x-4 gap-y-4">
            <Form.Item label="关键字" className="!mb-0">
              <Input
                className="w-full"
                placeholder="请输入账号或姓名"
                allowClear
                value={keyword}
                onChange={e => setKeyword(e.target.value)}
                onPressEnter={handleSearch}
                onClear={handleReset}
              />
            </Form.Item>
            <Form.Item className="col-start-2 !mb-0">
              <div className="flex gap-3">
                <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                  查询
                </Button>
                <Button icon={<ReloadOutlined />} onClick={handleReset}>
                  重置
                </Button>
              </div>
            </Form.Item>
          </div>
        </Form>
      </div>

      <div className="panel-card flex min-h-0 flex-1 flex-col">
        <div className="mb-4 flex shrink-0 items-center gap-3">
          <Button
            danger
            icon={<DeleteOutlined />}
            disabled={!selectedRows.length}
            onClick={handleBatchDelete}
          >
            批量删除
          </Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            新增
          </Button>
        </div>

        <ProTable<UserListItem>
          autoHeight
          rowSelection={{
            selectedRowKeys,
            onChange: (keys, rows) => {
              setSelectedRowKeys(keys)
              setSelectedRows(rows)
            },
            getCheckboxProps: row => ({ disabled: !row._disabled }),
          }}
          columns={columns}
          dataSource={tableData}
          loading={isFetching}
          scroll={{ x: 900 }}
          pagination={{
            current: page,
            pageSize,
            total,
            onChange: (nextPage, nextPageSize) => {
              setPage(nextPage)
              setPageSize(nextPageSize)
            },
          }}
        />
      </div>

      <UserForm
        key={formKey}
        open={formOpen}
        editingRow={editingRow}
        onClose={() => setFormOpen(false)}
        onSuccess={handleSuccess}
      />
    </div>
  )
}
