// vue3-admin/src/layouts/components/UpdatePwd.vue
<script setup lang="ts">
import { ref, reactive, useTemplateRef } from 'vue'
import { useRouter } from 'vue-router'
import { useMutation } from '@tanstack/vue-query'
import type { FormRules } from 'element-plus'
import type { UpdatePwdPayload } from '@/api/system/sysUser'
import * as sysUserApi from '@/api/system/sysUser'
import { useUserStore } from '@/stores/modules/user'
import { usePermissionStore } from '@/stores/modules/permission'
import { encryptPwdRsa } from '@/utils/encrypt'
import { message } from '@/utils/feedback'

const router = useRouter()
const userStore = useUserStore()
const permissionStore = usePermissionStore()

const visible = ref(false)
const formRef = useTemplateRef('formRef')

const INITIAL_FORM = {
  oldPwd: '',
  newPwd1: '',
  newPwd2: '',
}

const formModel = reactive({ ...INITIAL_FORM })

const rules: FormRules = {
  oldPwd: [{ required: true, message: '请输入旧密码', trigger: 'blur' }],
  newPwd1: [
    { required: true, message: '请输入新密码', trigger: 'blur' },
    {
      pattern: /^(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,}$/,
      message: '至少6位，且至少包含1个特殊字符（! @ # $ % ^ & *）',
      trigger: 'blur',
    },
  ],
  newPwd2: [
    {
      required: true,
      validator: (_rule, value, callback) => {
        if (!value) {
          callback(new Error('请再次输入新密码'))
        } else if (value !== formModel.newPwd1) {
          callback(new Error('两次输入的密码不一致'))
        } else {
          callback()
        }
      },
      trigger: 'blur',
    },
  ],
}

const saveMutation = useMutation({
  mutationFn: (payload: UpdatePwdPayload) => sysUserApi.updateUserPwd(payload),
  onSuccess: () => {
    message.success('密码修改成功，请重新登录')
    userStore.resetToken()
    permissionStore.resetRoutes()
    router.push('/login')
  },
})

function resetForm() {
  Object.assign(formModel, INITIAL_FORM)
  formRef.value?.clearValidate()
}

function open() {
  resetForm()
  visible.value = true
}

async function handleSubmit() {
  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) return

  saveMutation.mutate({
    oldPwd: encryptPwdRsa(formModel.oldPwd),
    newPwd1: encryptPwdRsa(formModel.newPwd1),
    newPwd2: encryptPwdRsa(formModel.newPwd2),
  })
}

defineExpose({ open })
</script>

<template>
  <el-dialog
    v-model="visible"
    title="修改密码"
    width="420px"
    align-center
    :close-on-click-modal="false"
  >
    <el-form
      ref="formRef"
      :model="formModel"
      :rules="rules"
      label-width="100px"
      :validate-on-rule-change="false"
      :disabled="saveMutation.isPending.value"
    >
      <el-form-item label="旧密码" prop="oldPwd">
        <el-input v-model="formModel.oldPwd" placeholder="请输入旧密码" autocomplete="off" />
      </el-form-item>
      <el-form-item label="新密码" prop="newPwd1">
        <el-input
          v-model="formModel.newPwd1"
          type="password"
          show-password
          placeholder="请输入新密码"
          autocomplete="new-password"
        />
      </el-form-item>
      <el-form-item label="确认新密码" prop="newPwd2">
        <el-input
          v-model="formModel.newPwd2"
          type="password"
          show-password
          placeholder="请再次输入新密码"
          autocomplete="new-password"
        />
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="visible = false">取消</el-button>
      <el-button type="primary" :loading="saveMutation.isPending.value" @click="handleSubmit">
        确定
      </el-button>
    </template>
  </el-dialog>
</template>

// react-admin/src/layouts/components/UpdatePwd.tsx
/**
 * 修改密码弹窗（Header 用户菜单入口）
 * ---------------------------------------------
 * 对应 vue3-admin UpdatePwd.vue：
 * - 三字段（原密码 / 新密码 / 确认密码），新密码正则「至少 6 位且含 1 个特殊字符」
 * - 提交前三字段各自 encryptPwdRsa；成功后退出会话并跳登录页
 * React 版改为受控 props（open / onClose）；footer=null + 表单内提交按钮，
 * 避开 useForm 与 Modal 懒渲染/销毁的连接时序问题；destroyOnHidden 保证
 * 每次打开表单为初始态。
 */
import { useNavigate } from 'react-router'
import { useMutation } from '@tanstack/react-query'
import { Button, Form, Input, Modal } from 'antd'
import { updateUserPwd } from '@/api/system/sysUser'
import { usePermissionStore } from '@/stores/modules/permission'
import { useUserStore } from '@/stores/modules/user'
import { encryptPwdRsa } from '@/utils/encrypt'
import { message } from '@/utils/feedback'

/** 新密码规则：至少 6 位且包含 1 个特殊字符（与 vue3-admin 一致） */
const PWD_PATTERN = /^(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,}$/

interface UpdatePwdValues {
  oldPwd: string
  newPwd1: string
  newPwd2: string
}

interface UpdatePwdProps {
  open: boolean
  onClose: () => void
}

export default function UpdatePwd({ open, onClose }: UpdatePwdProps) {
  const navigate = useNavigate()

  const { mutate, isPending } = useMutation({
    mutationFn: (values: UpdatePwdValues) =>
      updateUserPwd({
        oldPwd: encryptPwdRsa(values.oldPwd),
        newPwd1: encryptPwdRsa(values.newPwd1),
        newPwd2: encryptPwdRsa(values.newPwd2),
      }),
    onSuccess: () => {
      message.success('密码修改成功，请重新登录')
      onClose()
      useUserStore.getState().resetToken()
      usePermissionStore.getState().resetRoutes()
      navigate('/login', { replace: true })
    },
  })

  return (
    <Modal
      title="修改密码"
      open={open}
      width={420}
      centered
      mask={{ closable: false }}
      footer={null}
      destroyOnHidden
      onCancel={onClose}
    >
      <Form<UpdatePwdValues> className="pt-2" onFinish={values => mutate(values)} requiredMark={false}>
        <Form.Item name="oldPwd" label="原密码" rules={[{ required: true, message: '请输入原密码' }]}>
          <Input.Password autoComplete="old-password" placeholder="请输入原密码" />
        </Form.Item>
        <Form.Item
          name="newPwd1"
          label="新密码"
          rules={[
            { required: true, message: '请输入新密码' },
            { pattern: PWD_PATTERN, message: '至少 6 位且包含 1 个特殊字符（!@#$%^&*）' },
          ]}
        >
          <Input.Password autoComplete="new-password" placeholder="至少 6 位且含 1 个特殊字符" />
        </Form.Item>
        <Form.Item
          name="newPwd2"
          label="确认新密码"
          dependencies={['newPwd1']}
          rules={[
            { required: true, message: '请再次输入新密码' },
            ({ getFieldValue }) => ({
              validator(_, value) {
                if (!value || getFieldValue('newPwd1') === value) return Promise.resolve()
                return Promise.reject(new Error('两次输入的密码不一致'))
              },
            }),
          ]}
        >
          <Input.Password autoComplete="new-password" placeholder="请再次输入新密码" />
        </Form.Item>
        <div className="flex justify-end gap-2 pt-2">
          <Button onClick={onClose}>取消</Button>
          <Button type="primary" htmlType="submit" loading={isPending}>
            确定
          </Button>
        </div>
      </Form>
    </Modal>
  )
}
